# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - galactica-travels-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Set up SQL database
        uses: azure/sql-action@v2.2
        with:
          connection-string: 'Server=galactica-travels-backend-server.postgres.database.azure.com;Port=5432;Database=galactica-travels-backend-database;User=xscdpwowui;Password=Y6U1730ASP8VVV4S$'
          path: './database/*.sql'
          action: 'publish'
          arguments: '/p:DropObjectsNotInSource=true' # Optional properties and parameters for SqlPackage Publish

      - name: Install npm packages
        run: |
          cd backend
          npm install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'galactica-travels-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FF8CFE4DA79C4976A7C0BA607D0A3434 }}
          package: .
